services:
  tg-bot:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    container_name: tg-bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${TELEGRAM_BOT_PORT}:${TELEGRAM_BOT_PORT}'
    networks:
      - local_network
      - shared_network

  redis:
    image: redis:6
    restart: always
    command: redis-server --save 60 1 --loglevel warning --requirepass root
    networks:
      - local_network

networks:
  shared_network:
    external: true
  local_network:
    driver: bridge